import { query } from '../db.ts'

interface MindmapNode {
  name: string
  type: 'project' | 'module' | 'submodule' | 'feature' | 'page'
  children: MindmapNode[]
}

export async function generateMindmapData(projectId: string, moduleId?: number): Promise<MindmapNode> {
  const project = await query(`SELECT name FROM projects WHERE id = $1`, [projectId])
  const modules = await query(
    `SELECT id, name, parent_id, depth FROM modules WHERE project_id = $1 ORDER BY path, order_index`, [projectId]
  )
  const features = await query(
    `SELECT id, name, module_id FROM features WHERE project_id = $1 ORDER BY order_index`, [projectId]
  )
  const pages = await query(
    `SELECT id, name, page_type FROM pages WHERE project_id = $1 ORDER BY order_index`, [projectId]
  )

  const buildTree = (parentId: number | null): MindmapNode[] => {
    return modules.rows
      .filter(m => m.parent_id === parentId)
      .map(m => ({
        name: m.name,
        type: (m.depth === 0 ? 'module' : 'submodule') as MindmapNode['type'],
        children: [
          ...buildTree(m.id),
          ...features.rows.filter(f => f.module_id === m.id).map(f => ({
            name: f.name, type: 'feature' as const, children: [],
          })),
        ],
      }))
  }

  const pagesNode: MindmapNode = {
    name: 'Pages', type: 'module',
    children: pages.rows.map(p => ({ name: `${p.name} (${p.page_type || 'page'})`, type: 'page' as const, children: [] })),
  }

  return {
    name: project.rows[0]?.name || 'Project',
    type: 'project',
    children: [...buildTree(null), pagesNode],
  }
}

export function mindmapToHtml(root: MindmapNode): string {
  const renderNode = (node: MindmapNode, depth = 0): string => {
    const colors: Record<string, string> = {
      project: 'bg-green-600 text-white', module: 'bg-green-100 text-green-800',
      submodule: 'bg-blue-50 text-blue-700', feature: 'bg-amber-50 text-amber-700', page: 'bg-purple-50 text-purple-700',
    }
    const cls = colors[node.type] || 'bg-gray-100 text-gray-700'
    const children = node.children.map(c => renderNode(c, depth + 1)).join('')
    return `<div class="ml-${Math.min(depth * 6, 24)} mb-2">
      <div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg ${cls} text-sm font-medium">
        <span class="w-2 h-2 rounded-full ${node.type === 'project' ? 'bg-white' : 'bg-current'} opacity-40"></span>
        ${node.name}
      </div>
      ${children ? `<div class="ml-4 mt-1 border-l-2 border-gray-200 pl-4">${children}</div>` : ''}
    </div>`
  }

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Mindmap — ${root.name}</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>body{font-family:'Inter',system-ui,sans-serif}@media print{body{font-size:11px}}</style>
</head><body class="bg-white p-10 max-w-5xl mx-auto">
<h1 class="text-2xl font-bold text-gray-900 mb-6">${root.name} — Project Mindmap</h1>
<div class="flex gap-4 mb-6 text-xs">
  <span class="px-2 py-1 bg-green-100 text-green-800 rounded">Module</span>
  <span class="px-2 py-1 bg-blue-50 text-blue-700 rounded">Sub-module</span>
  <span class="px-2 py-1 bg-amber-50 text-amber-700 rounded">Feature</span>
  <span class="px-2 py-1 bg-purple-50 text-purple-700 rounded">Page</span>
</div>
${renderNode(root)}
<p class="text-xs text-gray-300 mt-10 text-center">Generated by Butterstack — ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
</body></html>`
}
