services:
  butterstack-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: butterstack-be
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AI_PROVIDER=${AI_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MODEL_STREAMLINE=${MODEL_STREAMLINE}
      - MODEL_TOKENS=${MODEL_TOKENS}
      - POSTGRES_DB_STRING=${POSTGRES_DB_STRING}
      - JWT_SECRET=${JWT_SECRET}
